config/routes.rb
Rails.application.routes.draw do
  resources :champion_views
  devise_for :users

  root 'welcome#index'


  get 'welcome/champions'

  get 'welcome/favorites'

  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/champion_view.rb
class ChampionView < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  before_action :authenticate_user!



end

app/controllers/champion_views_controller.rb
class ChampionViewsController < ApplicationController
  before_action :set_champion_view, only: [:show, :edit, :update, :destroy]

  # GET /champion_views
  # GET /champion_views.json
  def index
    @champion_views = ChampionView.all
  end

  # GET /champion_views/1
  # GET /champion_views/1.json
  def show
  end

  # GET /champion_views/new
  def new
    @champion_view = ChampionView.new
  end

  # GET /champion_views/1/edit
  def edit
  end

  # POST /champion_views
  # POST /champion_views.json
  def create
    @champion_view = ChampionView.new(champion_view_params)

    respond_to do |format|
      if @champion_view.save
        format.html { redirect_to @champion_view, notice: 'Champion view was successfully created.' }
        format.json { render :show, status: :created, location: @champion_view }
      else
        format.html { render :new }
        format.json { render json: @champion_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /champion_views/1
  # PATCH/PUT /champion_views/1.json
  def update
    respond_to do |format|
      if @champion_view.update(champion_view_params)
        format.html { redirect_to @champion_view, notice: 'Champion view was successfully updated.' }
        format.json { render :show, status: :ok, location: @champion_view }
      else
        format.html { render :edit }
        format.json { render json: @champion_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /champion_views/1
  # DELETE /champion_views/1.json
  def destroy
    @champion_view.destroy
    respond_to do |format|
      format.html { redirect_to champion_views_url, notice: 'Champion view was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_champion_view
      @champion_view = ChampionView.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def champion_view_params
      params.require(:champion_view).permit(:slide)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def champions
  end

  def favorites
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/champion_views_helper.rb
module ChampionViewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/champion_views/_form.html.erb
<%= form_with(model: champion_view, local: true) do |form| %>
  <% if champion_view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(champion_view.errors.count, "error") %> prohibited this champion_view from being saved:</h2>

      <ul>
      <% champion_view.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :slide %>
    <%= form.text_field :slide, id: :champion_view_slide %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/champion_views/edit.html.erb
<h1>Editing Champion View</h1>

<%= render 'form', champion_view: @champion_view %>

<%= link_to 'Show', @champion_view %> |
<%= link_to 'Back', champion_views_path %>

app/views/champion_views/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Champion Views</h1>

<table>
  <thead>
    <tr>
      <th>Slide</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @champion_views.each do |champion_view| %>
      <tr>
        <td><%= champion_view.slide %></td>
        <td><%= link_to 'Show', champion_view %></td>
        <td><%= link_to 'Edit', edit_champion_view_path(champion_view) %></td>
        <td><%= link_to 'Destroy', champion_view, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Champion View', new_champion_view_path %>

app/views/champion_views/new.html.erb
<h1>New Champion View</h1>

<%= render 'form', champion_view: @champion_view %>

<%= link_to 'Back', champion_views_path %>

app/views/champion_views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Slide:</strong>
  <%= @champion_view.slide %>
</p>

<%= link_to 'Edit', edit_champion_view_path(@champion_view) %> |
<%= link_to 'Back', champion_views_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RitoWhy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <div class="container"><!--don't know if i even need this? -->
          <div id="login_container">
          </div>
        </div>





    <% if user_signed_in? %>
   <div class="container" >
     <div class="pull-right">
       <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
     </div>
   </div>
   <% end %>


<br>
   <div class="button">
     <%= button_to "Champs", welcome_champions_path, :method => "get" %>
   </div>

<br>

   <div class="button">
       <%= button_to "Favorites", welcome_favorites_path, :method => "get" %>
   </div>

<br>

   <div class="button">
       <%= button_to "Welcome", root_path, :method => "get" %>
  </div>




    <%= yield %>
  </body>
</html>

app/views/welcome/champions.html.erb
<h1>Welcome#champions</h1>
<p>Find me in app/views/welcome/champions.html.erb</p>

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }
  </style>
</head>
<body>

<div class="container">
  <h2>Activate Carousel with JavaScript</h2>
  <div id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li class="item1 active"></li>
      <li class="item2"></li>
      <li class="item3"></li>
      <li class="item4"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

      <div class="item active">
        <img src="app/assets/images/Aatrox.jpg" alt="Aatrox" width="460" height="345">
        <div class="carousel-caption">
          <h3>Aatrox</h3>
          <p>Stupid champion 1</p>
        </div>
      </div>

      <div class="item">
        <img src="app/assets/images/Brand.jpg" alt="Brand" width="460" height="345">
        <div class="carousel-caption">
          <h3>Brand</h3>
          <p>Another dumb champion</p>
        </div>
      </div>

      <div class="item">
        <img src="app/assets/images/Galio.jpg" alt="Galio" width="460" height="345">
        <div class="carousel-caption">
          <h3>Galio</h3>
          <p>yet another broken champion</p>
        </div>
      </div>

      <div class="item">
        <img src="app/assets/images/Heimerdinger.jpg" alt="Heimer" width="460" height="345">
        <div class="carousel-caption">
          <h3>Heimerdinger</h3>
          <p>Just baroken</p>
        </div>
      </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<script>
$(document).ready(function(){
    // Activate Carousel
    $("#myCarousel").carousel();

    // Enable Carousel Indicators
    $(".item1").click(function(){
        $("#myCarousel").carousel(0);
    });
    $(".item2").click(function(){
        $("#myCarousel").carousel(1);
    });
    $(".item3").click(function(){
        $("#myCarousel").carousel(2);
    });
    $(".item4").click(function(){
        $("#myCarousel").carousel(3);
    });

    // Enable Carousel Controls
    $(".left").click(function(){
        $("#myCarousel").carousel("prev");
    });
    $(".right").click(function(){
        $("#myCarousel").carousel("next");
    });
});
</script>

</body>
</html>

app/views/welcome/favorites.html.erb
<h1>Welcome#favorites</h1>
<p>Find me in app/views/welcome/favorites.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

  <h1>Welcome, <%= current_user.email %></h1>